name: e_commerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Utility
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.2
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.6
  carousel_slider: ^4.2.1

  # State management
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/dashboard/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/profile/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
