// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWxeSDKv9BboR6pU4wKzAYkTmyqfUgqI',
    appId: '1:958877651955:web:97f97e54061abd24e63886',
    messagingSenderId: '958877651955',
    projectId: 'flutter-project-b79af',
    authDomain: 'flutter-project-b79af.firebaseapp.com',
    storageBucket: 'flutter-project-b79af.firebasestorage.app',
    measurementId: 'G-16WZLB6C7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZBelAyA77qrVB6u5HcvcV_aBtuguULU',
    appId: '1:958877651955:android:d5636738dbfd6b4ce63886',
    messagingSenderId: '958877651955',
    projectId: 'flutter-project-b79af',
    storageBucket: 'flutter-project-b79af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJgUSFL_Dji3zficqjiQ08itxGjvPFy90',
    appId: '1:958877651955:ios:3d8e20ac0905fcbde63886',
    messagingSenderId: '958877651955',
    projectId: 'flutter-project-b79af',
    storageBucket: 'flutter-project-b79af.firebasestorage.app',
    androidClientId: '958877651955-9sh71rqcognc2vhhqrfeqb60rlkcv46a.apps.googleusercontent.com',
    iosClientId: '958877651955-jh130106h0i6cka2n8fdbpai7m7dn51p.apps.googleusercontent.com',
    iosBundleId: 'com.rudrakha.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJgUSFL_Dji3zficqjiQ08itxGjvPFy90',
    appId: '1:958877651955:ios:3d8e20ac0905fcbde63886',
    messagingSenderId: '958877651955',
    projectId: 'flutter-project-b79af',
    storageBucket: 'flutter-project-b79af.firebasestorage.app',
    androidClientId: '958877651955-9sh71rqcognc2vhhqrfeqb60rlkcv46a.apps.googleusercontent.com',
    iosClientId: '958877651955-jh130106h0i6cka2n8fdbpai7m7dn51p.apps.googleusercontent.com',
    iosBundleId: 'com.rudrakha.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGWxeSDKv9BboR6pU4wKzAYkTmyqfUgqI',
    appId: '1:958877651955:web:1c531911652872f0e63886',
    messagingSenderId: '958877651955',
    projectId: 'flutter-project-b79af',
    authDomain: 'flutter-project-b79af.firebaseapp.com',
    storageBucket: 'flutter-project-b79af.firebasestorage.app',
    measurementId: 'G-3CH3E1P1RT',
  );

}